from __future__ import annotations

from contracts.factor_research import FactorResearchSpec, ValidationThreshold


ALPHA101_SOURCE = "WorldQuant 101 Formulaic Alphas"
ALPHA101_VERSION = "v2026.06"
ALPHA101_COMMON_THRESHOLDS = [
    ValidationThreshold("formula_match_ratio", ">=", 1.0, "代码实现与规格书公式逐项一致。"),
    ValidationThreshold("field_mapping_match_ratio", ">=", 1.0, "字段、复权、频率和股票池口径一致。"),
    ValidationThreshold("sample_point_error_ratio", "<=", 0.0, "抽样点位误差为零。"),
    ValidationThreshold("cross_section_spearman", ">=", 0.99, "与外部真值做截面对齐。"),
]


ALPHA101_IMPLEMENTED_DETAILS: dict[int, dict[str, object]] = {
    1: {
        "formula": "(rank(Ts_ArgMax(SignedPower(((returns < 0) ? stddev(returns, 20) : close), 2.), 5)) - 0.5)",
        "description": "下跌时使用 20 日收益波动率、否则使用收盘价，再做 5 日 argmax 横截面排序。",
        "required_fields": ["close"],
        "parameters": {"std_window": 20, "argmax_window": 5},
        "notes": ["需要先计算 1 日 returns。", "输出为横截面 rank 后减 0.5。"],
    },
    2: {
        "formula": "(-1 * correlation(rank(delta(log(volume), 2)), rank(((close - open) / open)), 6))",
        "description": "成交量对数变化与日内收益率排序之间的 6 日滚动相关反向因子。",
        "required_fields": ["open", "close", "volume"],
        "parameters": {"delta_window": 2, "corr_window": 6},
        "notes": ["volume 先取 log 再做 2 日 delta。"],
    },
    3: {
        "formula": "(-1 * correlation(rank(open), rank(volume), 10))",
        "description": "开盘价排序与成交量排序的 10 日滚动相关反向因子。",
        "required_fields": ["open", "volume"],
        "parameters": {"corr_window": 10},
        "notes": ["先做横截面 rank，再做按证券维度滚动相关。"],
    },
    4: {
        "formula": "(-1 * Ts_Rank(rank(low), 9))",
        "description": "最低价横截面排序的 9 日时序排序反向因子。",
        "required_fields": ["low"],
        "parameters": {"ts_rank_window": 9},
        "notes": ["先做横截面 rank，再做时间序列 rank。"],
    },
    5: {
        "formula": "(rank((open - (sum(vwap, 10) / 10))) * (-1 * abs(rank((close - vwap)))))",
        "description": "开盘价相对 10 日均值 VWAP 偏离与收盘价相对当日 VWAP 偏离的组合因子。",
        "required_fields": ["open", "close", "high", "low", "volume", "amount"],
        "parameters": {"vwap_mean_window": 10},
        "notes": ["VWAP 采用 amount / volume，缺失时回退到 OHLC 均值。"],
    },
    6: {
        "formula": "(-1 * correlation(open, volume, 10))",
        "description": "开盘价与成交量的 10 日滚动相关反向因子。",
        "required_fields": ["open", "volume"],
        "parameters": {"corr_window": 10},
        "notes": ["按证券维度滚动相关。"],
    },
    7: {
        "formula": "((adv20 < volume) ? ((-1 * ts_rank(abs(delta(close, 7)), 60)) * sign(delta(close, 7))) : (-1 * 1))",
        "description": "成交量放大时使用 7 日价格变化幅度的 60 日时序排序，否则固定为 -1。",
        "required_fields": ["close", "volume", "amount"],
        "parameters": {"adv_window": 20, "delta_window": 7, "ts_rank_window": 60},
        "notes": ["adv20 这里以成交额 20 日均值近似。"],
    },
    8: {
        "formula": "(-1 * rank(((sum(open, 5) * sum(returns, 5)) - delay((sum(open, 5) * sum(returns, 5)), 10))))",
        "description": "5 日开盘价累计与 5 日收益累计乘积相对 10 日前的变化反向排序因子。",
        "required_fields": ["open", "close"],
        "parameters": {"sum_window": 5, "delay_window": 10},
        "notes": ["需要先计算 returns。"],
    },
    9: {
        "formula": "((0 < ts_min(delta(close, 1), 5)) ? delta(close, 1) : ((ts_max(delta(close, 1), 5) < 0) ? delta(close, 1) : (-1 * delta(close, 1))))",
        "description": "根据近 5 日价格变化方向一致性决定是否对 1 日价格变化取反。",
        "required_fields": ["close"],
        "parameters": {"delta_window": 1, "state_window": 5},
        "notes": ["这是时序条件分支因子，不做横截面排序。"],
    },
    10: {
        "formula": "rank(((0 < ts_min(delta(close, 1), 4)) ? delta(close, 1) : ((ts_max(delta(close, 1), 4) < 0) ? delta(close, 1) : (-1 * delta(close, 1)))))",
        "description": "Alpha10 在 Alpha9 的条件分支基础上增加横截面排序。",
        "required_fields": ["close"],
        "parameters": {"delta_window": 1, "state_window": 4},
        "notes": ["先构造 inner，再做横截面 rank。"],
    },
    12: {
        "formula": "(sign(delta(volume, 1)) * (-1 * delta(close, 1)))",
        "description": "成交量变化方向与收盘价一日变化的反向乘积因子。",
        "required_fields": ["close", "volume"],
        "parameters": {"delta_window": 1},
        "notes": ["属于简单时序差分因子，不做横截面排序。"],
    },
    13: {
        "formula": "(-1 * rank(covariance(rank(close), rank(volume), 5)))",
        "description": "收盘价排序与成交量排序的 5 日滚动协方差反向排序因子。",
        "required_fields": ["close", "volume"],
        "parameters": {"cov_window": 5},
        "notes": ["先做横截面 rank，再做按证券维度滚动协方差。"],
    },
    15: {
        "formula": "(-1 * sum(rank(correlation(rank(high), rank(volume), 3)), 3))",
        "description": "最高价排序与成交量排序相关性的 3 日横截面排序，再做 3 日求和反向因子。",
        "required_fields": ["high", "volume"],
        "parameters": {"corr_window": 3, "sum_window": 3},
        "notes": ["先计算 rank(high)、rank(volume)。"],
    },
    16: {
        "formula": "(-1 * rank(covariance(rank(high), rank(volume), 5)))",
        "description": "最高价排序与成交量排序的 5 日滚动协方差反向排序因子。",
        "required_fields": ["high", "volume"],
        "parameters": {"cov_window": 5},
        "notes": ["与 Alpha13 类似，但价格字段改为 high。"],
    },
    17: {
        "formula": "(((-1 * rank(ts_rank(close, 10))) * rank(delta(delta(close, 1), 1)) * rank(ts_rank((volume / adv20), 5))) + 1)",
        "description": "综合 10 日收盘价时序排序、二阶价格变化与成交量相对活跃度的复合因子。",
        "required_fields": ["close", "volume"],
        "parameters": {"close_rank_window": 10, "adv_window": 20, "volume_rank_window": 5},
        "notes": ["adv20 这里使用 volume 的 20 日均值。"],
    },
    18: {
        "formula": "(-1 * rank(((stddev(abs(close - open), 10) + (close - open)) + correlation(close, open, 10))))",
        "description": "结合日内价差波动、当日价差和 10 日开收盘相关性的反向排序因子。",
        "required_fields": ["open", "close"],
        "parameters": {"std_window": 10, "corr_window": 10},
        "notes": ["先构造 inner，再做横截面 rank。"],
    },
    19: {
        "formula": "((-1 * sign(delta(close, 7))) * (1 + rank(decay_linear((close / delay(close, 1) - 1), 5))))",
        "description": "7 日趋势方向与 5 日线性衰减收益排序的组合因子。",
        "required_fields": ["close"],
        "parameters": {"trend_window": 7, "decay_window": 5},
        "notes": ["线性衰减对 1 日收益序列进行加权。"],
    },
    20: {
        "formula": "((-1 * rank(open - delay(high, 1))) * rank(open - delay(close, 1)) * rank(open - delay(low, 1)))",
        "description": "开盘价相对前一日高低收三项偏离的横截面排序乘积因子。",
        "required_fields": ["open", "high", "low", "close"],
        "parameters": {"delay_window": 1},
        "notes": ["三个偏离项分别横截面 rank 后相乘。"],
    },
    21: {
        "formula": "(-1 * (rank(correlation(close, volume, 5)) * rank(correlation(close, volume, 20))))",
        "description": "收盘价与成交量在 5 日和 20 日相关性的双窗口复合反向因子。",
        "required_fields": ["close", "volume"],
        "parameters": {"short_corr_window": 5, "long_corr_window": 20},
        "notes": ["两个相关项先分别做横截面 rank。"],
    },
    26: {
        "formula": "(-1 * ts_max(correlation(ts_rank(volume, 5), ts_rank(high, 5), 5), 3))",
        "description": "成交量与最高价的 5 日时序排序相关性在近 3 日的最大值反向因子。",
        "required_fields": ["high", "volume"],
        "parameters": {"rank_window": 5, "corr_window": 5, "max_window": 3},
        "notes": ["全部按证券维度先做时序 rank 再计算相关。"],
    },
    28: {
        "formula": "scale(((correlation(adv20, low, 20) * -1) + rank(covariance(rank(close), rank(volume), 5))))",
        "description": "低价与活跃度相关性和价量协方差排序的组合，并做横截面 scale 归一化。",
        "required_fields": ["close", "low", "volume"],
        "parameters": {"adv_window": 20, "corr_window": 20, "cov_window": 5},
        "notes": ["scale 采用截面绝对值和归一化。"],
    },
    33: {
        "formula": "rank((-1 + (close / delay(close, 1))))",
        "description": "单日收益率的横截面排序因子。",
        "required_fields": ["close"],
        "parameters": {"delay_window": 1},
        "notes": ["等价于对 1 日收益做横截面 rank。"],
    },
    34: {
        "formula": "mean(((delta(close, 1) < 0) ? stddev(delta(close, 1), 20) : (close / delay(close, 1))), 20)",
        "description": "下跌时取 20 日价差波动率，否则取价格比值，再做 20 日均值。",
        "required_fields": ["close"],
        "parameters": {"std_window": 20, "mean_window": 20},
        "notes": ["这里的 delta(close,1) 使用 close - delay(close,1)。"],
    },
    37: {
        "formula": "(-1 * rank(correlation(delay(open, 1), delay(volume, 1), 3)))",
        "description": "滞后一期的开盘价与成交量之间 3 日相关性的反向排序因子。",
        "required_fields": ["open", "volume"],
        "parameters": {"delay_window": 1, "corr_window": 3},
        "notes": ["相关项完成后再做横截面 rank。"],
    },
    41: {
        "formula": "((high * low)^0.5 - vwap)",
        "description": "最高价与最低价几何均值相对 VWAP 的偏离因子。",
        "required_fields": ["high", "low", "volume", "amount"],
        "parameters": {},
        "notes": ["VWAP 采用 amount / volume。"],
    },
    42: {
        "formula": "((-1 * rank(stddev(high, 10))) * correlation(high, volume, 10))",
        "description": "最高价波动横截面排序与价量相关性的复合反向因子。",
        "required_fields": ["high", "volume"],
        "parameters": {"std_window": 10, "corr_window": 10},
        "notes": ["std(high,10) 先做横截面 rank。"],
    },
    44: {
        "formula": "(-1 * correlation(high, rank(volume), 5))",
        "description": "最高价与成交量横截面排序之间的 5 日相关性反向因子。",
        "required_fields": ["high", "volume"],
        "parameters": {"corr_window": 5},
        "notes": ["只对 volume 做横截面 rank。"],
    },
    49: {
        "formula": "sum(up_move, 12) / (sum(up_move, 12) + sum(down_move, 12))",
        "description": "基于高低价相对前一日变化构造上下行波动强度比值。",
        "required_fields": ["high", "low"],
        "parameters": {"sum_window": 12},
        "notes": ["up_move/down_move 按 WorldQuant 条件分支定义。"],
    },
    50: {
        "formula": "(-1 * ts_max(rank(correlation(rank(volume), rank(vwap), 5)), 3))",
        "description": "成交量排序与 VWAP 排序相关性的截面排序在近 3 日最大值反向因子。",
        "required_fields": ["volume", "amount"],
        "parameters": {"corr_window": 5, "max_window": 3},
        "notes": ["VWAP 采用 amount / volume。"],
    },
    53: {
        "formula": "(-1 * delta((((close - low) - (high - close)) / (close - low)), 9))",
        "description": "价格在日内区间中的相对位置经过 9 日变化后的反向因子。",
        "required_fields": ["close", "high", "low"],
        "parameters": {"delta_window": 9},
        "notes": ["分母 close - low 为 0 时置空。"],
    },
    55: {
        "formula": "(-1 * correlation(rank(close - ts_min(low, 5)), rank(volume), 5))",
        "description": "收盘价相对 5 日最低价偏离的排序与成交量排序之间的 5 日相关反向因子。",
        "required_fields": ["close", "low", "volume"],
        "parameters": {"min_window": 5, "corr_window": 5},
        "notes": ["先做 close - ts_min(low,5) 的横截面 rank。"],
    },
}

ALPHA101_IMPLEMENTED_DETAILS.update(
    {
        11: {
            "formula": "((rank(ts_max((vwap - close), 3)) + rank(ts_min((vwap - close), 3))) * rank(delta(volume, 3)))",
            "description": "VWAP 相对收盘价的短窗极值与 3 日成交量变化排序的复合因子。",
            "required_fields": ["close", "volume", "amount"],
            "parameters": {"extreme_window": 3, "delta_window": 3},
            "notes": ["先计算 vwap-close，再取 3 日时序极值。"],
        },
        14: {
            "formula": "((-1 * rank(delta(returns, 3))) * correlation(open, volume, 10))",
            "description": "3 日收益变化排序与开盘价-成交量 10 日相关性的乘积反向因子。",
            "required_fields": ["open", "close", "volume"],
            "parameters": {"delta_window": 3, "corr_window": 10},
            "notes": ["需要先计算 returns。"],
        },
        17: {
            "formula": "(((-1 * rank(ts_rank(close, 10))) * rank(delta(delta(close, 1), 1))) * rank(ts_rank((volume / adv20), 5)))",
            "description": "10 日收盘价时序排序、二阶价格变化与成交额活跃度时序排序的复合因子。",
            "required_fields": ["close", "volume", "amount"],
            "parameters": {"close_rank_window": 10, "adv_window": 20, "activity_rank_window": 5},
            "notes": ["原稿表达中不包含额外 +1 常数项。"],
        },
        18: {
            "formula": "(-1 * rank(((stddev(abs((close - open)), 5) + (close - open)) + correlation(close, open, 10))))",
            "description": "5 日绝对日内价差波动、当日价差与 10 日开收盘相关性的反向排序因子。",
            "required_fields": ["open", "close"],
            "parameters": {"std_window": 5, "corr_window": 10},
            "notes": ["以论文原稿为准，std 窗口为 5。"],
        },
        19: {
            "formula": "((-1 * sign(((close - delay(close, 7)) + delta(close, 7)))) * (1 + rank((1 + sum(returns, 250)))))",
            "description": "7 日价格动量方向与 250 日累计收益排序的组合因子。",
            "required_fields": ["close"],
            "parameters": {"delay_window": 7, "delta_window": 7, "sum_window": 250},
            "notes": ["按原稿使用 1 + sum(returns,250) 的横截面 rank。"],
        },
        21: {
            "formula": "((((sum(close, 8) / 8) + stddev(close, 8)) < (sum(close, 2) / 2)) ? (-1 * 1) : (((sum(close, 2) / 2) < ((sum(close, 8) / 8) - stddev(close, 8))) ? 1 : (((1 < (volume / adv20)) || ((volume / adv20) == 1)) ? 1 : (-1 * 1))))",
            "description": "基于 8 日均值与波动、2 日均值和活跃度阈值的条件分支因子。",
            "required_fields": ["close", "volume", "amount"],
            "parameters": {"mean_window_long": 8, "mean_window_short": 2, "std_window": 8, "adv_window": 20},
            "notes": ["最终输出为条件分支的 1/-1。"],
        },
        22: {
            "formula": "(-1 * (delta(correlation(high, volume, 5), 5) * rank(stddev(close, 20))))",
            "description": "高价-成交量相关性的 5 日变化与收盘价波动排序的复合反向因子。",
            "required_fields": ["high", "close", "volume"],
            "parameters": {"corr_window": 5, "delta_window": 5, "std_window": 20},
            "notes": ["先求 correlation(high, volume, 5)，再做 5 日 delta。"],
        },
        23: {
            "formula": "(((sum(high, 20) / 20) < high) ? (-1 * delta(high, 2)) : 0)",
            "description": "当高价高于 20 日均值时使用 2 日高价变化的反向值，否则为 0。",
            "required_fields": ["high"],
            "parameters": {"mean_window": 20, "delta_window": 2},
            "notes": ["纯条件分支时序因子。"],
        },
        24: {
            "formula": "((((delta((sum(close, 100) / 100), 100) / delay(close, 100)) < 0.05) || ((delta((sum(close, 100) / 100), 100) / delay(close, 100)) == 0.05)) ? (-1 * (close - ts_min(close, 100))) : (-1 * delta(close, 3)))",
            "description": "基于 100 日均价变化阈值，在长期低点偏离和 3 日价格变化之间切换的因子。",
            "required_fields": ["close"],
            "parameters": {"mean_window": 100, "delta_mean_window": 100, "delay_window": 100, "fallback_delta_window": 3},
            "notes": ["阈值为 0.05。"],
        },
        25: {
            "formula": "rank(((((-1 * returns) * adv20) * vwap) * (high - close)))",
            "description": "收益、活跃度、VWAP 和上影线组合后的横截面排序因子。",
            "required_fields": ["close", "high", "amount", "volume"],
            "parameters": {"adv_window": 20},
            "notes": ["需要先计算 returns 与 vwap。"],
        },
        27: {
            "formula": "((0.5 < rank((sum(correlation(rank(volume), rank(vwap), 6), 2) / 2.0))) ? (-1 * 1) : 1)",
            "description": "成交量排序与 VWAP 排序相关性的 2 日均值排名触发的二元因子。",
            "required_fields": ["volume", "amount"],
            "parameters": {"corr_window": 6, "mean_window": 2},
            "notes": ["输出仅为 1 或 -1。"],
        },
        28: {
            "formula": "scale(((correlation(adv20, low, 5) + ((high + low) / 2)) - close))",
            "description": "低价与活跃度相关性叠加中间价偏离后的 scale 因子。",
            "required_fields": ["close", "high", "low", "amount", "volume"],
            "parameters": {"adv_window": 20, "corr_window": 5},
            "notes": ["以论文原稿为准，不再混入价量协方差 rank。"],
        },
        30: {
            "formula": "(((1.0 - rank(((sign((close - delay(close, 1))) + sign((delay(close, 1) - delay(close, 2)))) + sign((delay(close, 2) - delay(close, 3)))))) * sum(volume, 5)) / sum(volume, 20))",
            "description": "基于三段价格方向符号和短长成交量之比的因子。",
            "required_fields": ["close", "volume"],
            "parameters": {"short_sum_window": 5, "long_sum_window": 20},
            "notes": ["三项 sign 相加后做横截面 rank。"],
        },
        31: {
            "formula": "((rank(rank(rank(decay_linear((-1 * rank(rank(delta(close, 10)))), 10)))) + rank((-1 * delta(close, 3)))) + sign(scale(correlation(adv20, low, 12))))",
            "description": "多重排序、衰减和活跃度-低价相关性的复合因子。",
            "required_fields": ["close", "low", "amount", "volume"],
            "parameters": {"delta_long_window": 10, "decay_window": 10, "delta_short_window": 3, "corr_window": 12, "adv_window": 20},
            "notes": ["包含多层横截面 rank 和 scale。"],
        },
        32: {
            "formula": "(scale(((sum(close, 7) / 7) - close)) + (20 * scale(correlation(vwap, delay(close, 5), 230))))",
            "description": "7 日均值偏离与 VWAP-滞后收盘价超长窗相关性的复合 scale 因子。",
            "required_fields": ["close", "amount", "volume"],
            "parameters": {"mean_window": 7, "delay_window": 5, "corr_window": 230},
            "notes": ["第二项系数为 20。"],
        },
        33: {
            "formula": "rank((-1 * ((1 - (open / close))^1)))",
            "description": "开收盘比值偏离的横截面排序因子。",
            "required_fields": ["open", "close"],
            "parameters": {},
            "notes": ["按原稿直接保留幂为 1 的写法。"],
        },
        34: {
            "formula": "rank(((1 - rank((stddev(returns, 2) / stddev(returns, 5)))) + (1 - rank(delta(close, 1)))))",
            "description": "短长窗收益波动比排名和 1 日价格变化排名的复合排序因子。",
            "required_fields": ["close"],
            "parameters": {"short_std_window": 2, "long_std_window": 5, "delta_window": 1},
            "notes": ["以 returns 为输入而不是 close 差分波动。"],
        },
        35: {
            "formula": "((Ts_Rank(volume, 32) * (1 - Ts_Rank(((close + high) - low), 16))) * (1 - Ts_Rank(returns, 32)))",
            "description": "成交量、价格结构项和收益时序排序的三项乘积因子。",
            "required_fields": ["close", "high", "low", "volume"],
            "parameters": {"volume_rank_window": 32, "price_rank_window": 16, "returns_rank_window": 32},
            "notes": ["需要先计算 returns。"],
        },
        36: {
            "formula": "(((((2.21 * rank(correlation((close - open), delay(volume, 1), 15))) + (0.7 * rank((open - close)))) + (0.73 * rank(Ts_Rank(delay((-1 * returns), 6), 5)))) + rank(abs(correlation(vwap, adv20, 6)))) + (0.6 * rank((((sum(close, 200) / 200) - open) * (close - open)))))",
            "description": "多项带权价格-成交量结构信号的加总因子。",
            "required_fields": ["open", "close", "volume", "amount"],
            "parameters": {"corr_window_1": 15, "delay_returns_window": 6, "ts_rank_window": 5, "adv_window": 20, "corr_window_2": 6, "mean_window": 200},
            "notes": ["按原稿保留 2.21、0.7、0.73、0.6 权重。"],
        },
        37: {
            "formula": "(rank(correlation(delay((open - close), 1), close, 200)) + rank((open - close)))",
            "description": "滞后开收盘差与收盘价的超长窗相关项，加上当日开收盘差排名。",
            "required_fields": ["open", "close"],
            "parameters": {"delay_window": 1, "corr_window": 200},
            "notes": ["以论文原稿为准，不是 delay(open)/delay(volume) 的短窗相关。"],
        },
        38: {
            "formula": "((-1 * rank(Ts_Rank(close, 10))) * rank((close / open)))",
            "description": "收盘价 10 日时序排序与当日开收比值排名的复合反向因子。",
            "required_fields": ["open", "close"],
            "parameters": {"ts_rank_window": 10},
            "notes": [],
        },
        39: {
            "formula": "((-1 * rank((delta(close, 7) * (1 - rank(decay_linear((volume / adv20), 9)))))) * (1 + rank(sum(returns, 250))))",
            "description": "7 日价格变化、活跃度衰减排名和长期累计收益排名的复合因子。",
            "required_fields": ["close", "volume", "amount"],
            "parameters": {"delta_window": 7, "adv_window": 20, "decay_window": 9, "sum_window": 250},
            "notes": [],
        },
        40: {
            "formula": "((-1 * rank(stddev(high, 10))) * correlation(high, volume, 10))",
            "description": "高价波动率排名与高价-成交量相关性的复合反向因子。",
            "required_fields": ["high", "volume"],
            "parameters": {"std_window": 10, "corr_window": 10},
            "notes": [],
        },
        42: {
            "formula": "(rank((vwap - close)) / rank((vwap + close)))",
            "description": "VWAP 相对收盘价偏离与 VWAP+收盘价排名之比因子。",
            "required_fields": ["close", "amount", "volume"],
            "parameters": {},
            "notes": ["以论文原稿为准，Alpha42 不是高价波动相关因子。"],
        },
        43: {
            "formula": "(ts_rank((volume / adv20), 20) * ts_rank((-1 * delta(close, 7)), 8))",
            "description": "活跃度时序排序与 7 日价格变化反向时序排序的乘积因子。",
            "required_fields": ["close", "volume", "amount"],
            "parameters": {"adv_window": 20, "activity_rank_window": 20, "delta_window": 7, "price_rank_window": 8},
            "notes": [],
        },
        45: {
            "formula": "(-1 * ((rank((sum(delay(close, 5), 20) / 20)) * correlation(close, volume, 2)) * rank(correlation(sum(close, 5), sum(close, 20), 2))))",
            "description": "滞后收盘均值排名、短窗价量相关与不同累计收盘价相关的复合反向因子。",
            "required_fields": ["close", "volume"],
            "parameters": {"delay_window": 5, "mean_window": 20, "corr_window_short": 2, "sum_window_short": 5, "sum_window_long": 20},
            "notes": [],
        },
        46: {
            "formula": "((0.25 < (((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10))) ? (-1 * 1) : (((((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10)) < 0) ? 1 : ((-1 * 1) * (close - delay(close, 1)))))",
            "description": "基于两段价格斜率差异的条件分支因子。",
            "required_fields": ["close"],
            "parameters": {"delay_long": 20, "delay_mid": 10},
            "notes": ["输出为 -1、1 或 -(close-delay(close,1))。"],
        },
        47: {
            "formula": "((((rank((1 / close)) * volume) / adv20) * ((high * rank((high - close))) / (sum(high, 5) / 5))) - rank((vwap - delay(vwap, 5))))",
            "description": "逆价、活跃度、上影线强度和 VWAP 滞后偏离组成的复合因子。",
            "required_fields": ["close", "high", "volume", "amount"],
            "parameters": {"adv_window": 20, "high_mean_window": 5, "vwap_delay_window": 5},
            "notes": [],
        },
        48: {
            "formula": "(indneutralize(((correlation(delta(close, 1), delta(delay(close, 1), 1), 250) * delta(close, 1)) / close), IndClass.subindustry) / sum(((delta(close, 1) / delay(close, 1))^2), 250))",
            "description": "经子行业中性化处理后的长窗相关-收益复合因子。",
            "required_fields": ["close", "subindustry"],
            "parameters": {"corr_window": 250, "sum_window": 250},
            "notes": ["需要 `subindustry` 分组列。"],
        },
        49: {
            "formula": "(((((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10)) < (-1 * 0.1)) ? 1 : ((-1 * 1) * (close - delay(close, 1))))",
            "description": "基于斜率阈值 -0.1 的条件分支价格变化因子。",
            "required_fields": ["close"],
            "parameters": {"delay_long": 20, "delay_mid": 10},
            "notes": ["以论文原稿为准，非 up/down move 比值。"],
        },
        50: {
            "formula": "(-1 * ts_max(rank(correlation(rank(volume), rank(vwap), 5)), 5))",
            "description": "成交量排序与 VWAP 排序相关性的排名在近 5 日最大值反向因子。",
            "required_fields": ["volume", "amount"],
            "parameters": {"corr_window": 5, "max_window": 5},
            "notes": [],
        },
        51: {
            "formula": "(((((delay(close, 20) - delay(close, 10)) / 10) - ((delay(close, 10) - close) / 10)) < (-1 * 0.05)) ? 1 : ((-1 * 1) * (close - delay(close, 1))))",
            "description": "基于斜率阈值 -0.05 的条件分支价格变化因子。",
            "required_fields": ["close"],
            "parameters": {"delay_long": 20, "delay_mid": 10},
            "notes": [],
        },
        52: {
            "formula": "((((-1 * ts_min(low, 5)) + delay(ts_min(low, 5), 5)) * rank(((sum(returns, 240) - sum(returns, 20)) / 220))) * ts_rank(volume, 5))",
            "description": "低价极值变化、长期-短期累计收益差排名和成交量时序排序的复合因子。",
            "required_fields": ["low", "close", "volume"],
            "parameters": {"min_window": 5, "delay_window": 5, "long_sum_window": 240, "short_sum_window": 20, "volume_rank_window": 5},
            "notes": ["需要先计算 returns。"],
        },
        54: {
            "formula": "((-1 * ((low - close) * (open^5))) / ((low - high) * (close^5)))",
            "description": "使用开收盘五次幂加权的日内结构因子。",
            "required_fields": ["open", "high", "low", "close"],
            "parameters": {},
            "notes": ["分母为 0 时置空。"],
        },
        55: {
            "formula": "(-1 * correlation(rank(((close - ts_min(low, 12)) / (ts_max(high, 12) - ts_min(low, 12)))), rank(volume), 6))",
            "description": "价格在 12 日区间中相对位置的排名与成交量排名之间的相关反向因子。",
            "required_fields": ["close", "high", "low", "volume"],
            "parameters": {"window": 12, "corr_window": 6},
            "notes": ["以论文原稿为准，不再使用 5 日最低价简化版。"],
        },
        56: {
            "formula": "(0 - (1 * (rank((sum(returns, 10) / sum(sum(returns, 2), 3))) * rank((returns * cap)))))",
            "description": "短期收益结构比值排名和收益乘市值排名的复合反向因子。",
            "required_fields": ["close", "cap"],
            "parameters": {"sum_window_long": 10, "sum_window_short": 2, "outer_sum_window": 3},
            "notes": ["需要 `cap` 列。"],
        },
        57: {
            "formula": "(0 - (1 * ((close - vwap) / decay_linear(rank(ts_argmax(close, 30)), 2))))",
            "description": "收盘价相对 VWAP 的偏离除以收盘价 argmax 排名衰减项的反向因子。",
            "required_fields": ["close", "amount", "volume"],
            "parameters": {"argmax_window": 30, "decay_window": 2},
            "notes": [],
        },
    }
)

ALPHA101_IMPLEMENTED_DETAILS.update(
    {
        29: {
            "formula": '(min(product(rank(rank(scale(log(sum(ts_min(rank(rank((-1 * rank(delta((close - 1), 5))))), 2), 1))))), 1), 5) + ts_rank(delay((-1 * returns), 6), 5))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha29 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        58: {
            "formula": '(-1 * Ts_Rank(decay_linear(correlation(IndNeutralize(vwap, IndClass.sector), volume, 3.92795), 7.89291), 5.50322))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha58 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'sector'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        59: {
            "formula": '(-1 * Ts_Rank(decay_linear(correlation(IndNeutralize(((vwap * 0.728317) + (vwap * (1 - 0.728317))), IndClass.industry), volume, 4.25197), 16.2289), 8.19648))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha59 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        60: {
            "formula": '(0 - (1 * ((2 * scale(rank(((((close - low) - (high - close)) / (high - low)) * volume)))) - scale(rank(ts_argmax(close, 10)))))) 12',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha60 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        61: {
            "formula": '(rank((vwap - ts_min(vwap, 16.1219))) < rank(correlation(vwap, adv180, 17.9282)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha61 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        62: {
            "formula": '((rank(correlation(vwap, sum(adv20, 22.4101), 9.91009)) < rank(((rank(open) + rank(open)) < (rank(((high + low) / 2)) + rank(high))))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha62 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        63: {
            "formula": '((rank(decay_linear(delta(IndNeutralize(close, IndClass.industry), 2.25164), 8.22237)) - rank(decay_linear(correlation(((vwap * 0.318108) + (open * (1 - 0.318108))), sum(adv180, 37.2467), 13.557), 12.2883))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha63 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        64: {
            "formula": '((rank(correlation(sum(((open * 0.178404) + (low * (1 - 0.178404))), 12.7054), sum(adv120, 12.7054), 16.6208)) < rank(delta(((((high + low) / 2) * 0.178404) + (vwap * (1 - 0.178404))), 3.69741))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha64 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        65: {
            "formula": '((rank(correlation(((open * 0.00817205) + (vwap * (1 - 0.00817205))), sum(adv60, 8.6911), 6.40374)) < rank((open - ts_min(open, 13.635)))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha65 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        66: {
            "formula": '((rank(decay_linear(delta(vwap, 3.51013), 7.23052)) + Ts_Rank(decay_linear(((((low * 0.96633) + (low * (1 - 0.96633))) - vwap) / (open - ((high + low) / 2))), 11.4157), 6.72611)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha66 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        67: {
            "formula": '((rank((high - ts_min(high, 2.14593)))^rank(correlation(IndNeutralize(vwap, IndClass.sector), IndNeutralize(adv20, IndClass.subindustry), 6.02936))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha67 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'sector', 'industry', 'subindustry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        68: {
            "formula": '((Ts_Rank(correlation(rank(high), rank(adv15), 8.91644), 13.9333) < rank(delta(((close * 0.518371) + (low * (1 - 0.518371))), 1.06157))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha68 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        69: {
            "formula": '((rank(ts_max(delta(IndNeutralize(vwap, IndClass.industry), 2.72412), 4.79344))^Ts_Rank(correlation(((close * 0.490655) + (vwap * (1 - 0.490655))), adv20, 4.92416), 9.0615)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha69 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        70: {
            "formula": '((rank(delta(vwap, 1.29456))^Ts_Rank(correlation(IndNeutralize(close, IndClass.industry), adv50, 17.8256), 17.9171)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha70 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        71: {
            "formula": 'max(Ts_Rank(decay_linear(correlation(Ts_Rank(close, 3.43976), Ts_Rank(adv180, 12.0647), 18.0175), 4.20501), 15.6948), Ts_Rank(decay_linear((rank(((low + open) - (vwap + vwap)))^2), 16.4662), 4.4388))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha71 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        72: {
            "formula": '(rank(decay_linear(correlation(((high + low) / 2), adv40, 8.93345), 10.1519)) / rank(decay_linear(correlation(Ts_Rank(vwap, 3.72469), Ts_Rank(volume, 18.5188), 6.86671), 2.95011)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha72 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        73: {
            "formula": '(max(rank(decay_linear(delta(vwap, 4.72775), 2.91864)), Ts_Rank(decay_linear(((delta(((open * 0.147155) + (low * (1 - 0.147155))), 2.03608) / ((open * 0.147155) + (low * (1 - 0.147155)))) * -1), 3.33829), 16.7411)) * -1) 13',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha73 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        74: {
            "formula": '((rank(correlation(close, sum(adv30, 37.4843), 15.1365)) < rank(correlation(rank(((high * 0.0261661) + (vwap * (1 - 0.0261661)))), rank(volume), 11.4791))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha74 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        75: {
            "formula": '(rank(correlation(vwap, volume, 4.24304)) < rank(correlation(rank(low), rank(adv50), 12.4413)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha75 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        76: {
            "formula": '(max(rank(decay_linear(delta(vwap, 1.24383), 11.8259)), Ts_Rank(decay_linear(Ts_Rank(correlation(IndNeutralize(low, IndClass.sector), adv81, 8.14941), 19.569), 17.1543), 19.383)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha76 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'sector'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        77: {
            "formula": 'min(rank(decay_linear(((((high + low) / 2) + high) - (vwap + high)), 20.0451)), rank(decay_linear(correlation(((high + low) / 2), adv40, 3.1614), 5.64125)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha77 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        78: {
            "formula": '(rank(correlation(sum(((low * 0.352233) + (vwap * (1 - 0.352233))), 19.7428), sum(adv40, 19.7428), 6.83313))^rank(correlation(rank(vwap), rank(volume), 5.77492)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha78 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        79: {
            "formula": '(rank(delta(IndNeutralize(((close * 0.60733) + (open * (1 - 0.60733))), IndClass.sector), 1.23438)) < rank(correlation(Ts_Rank(vwap, 3.60973), Ts_Rank(adv150, 9.18637), 14.6644)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha79 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'sector'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        80: {
            "formula": '((rank(Sign(delta(IndNeutralize(((open * 0.868128) + (high * (1 - 0.868128))), IndClass.industry), 4.04545)))^Ts_Rank(correlation(high, adv10, 5.11456), 5.53756)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha80 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        81: {
            "formula": '((rank(Log(product(rank((rank(correlation(vwap, sum(adv10, 49.6054), 8.47743))^4)), 14.9655))) < rank(correlation(rank(vwap), rank(volume), 5.07914))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha81 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        82: {
            "formula": '(min(rank(decay_linear(delta(open, 1.46063), 14.8717)), Ts_Rank(decay_linear(correlation(IndNeutralize(volume, IndClass.sector), ((open * 0.634196) + (open * (1 - 0.634196))), 17.4842), 6.92131), 13.4283)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha82 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'sector'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        83: {
            "formula": '((rank(delay(((high - low) / (sum(close, 5) / 5)), 2)) * rank(rank(volume))) / (((high - low) / (sum(close, 5) / 5)) / (vwap - close)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha83 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        84: {
            "formula": 'SignedPower(Ts_Rank((vwap - ts_max(vwap, 15.3217)), 20.7127), delta(close, 4.96796))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha84 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        85: {
            "formula": '(rank(correlation(((high * 0.876703) + (close * (1 - 0.876703))), adv30, 9.61331))^rank(correlation(Ts_Rank(((high + low) / 2), 3.70596), Ts_Rank(volume, 10.1595), 7.11408)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha85 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        86: {
            "formula": '((Ts_Rank(correlation(close, sum(adv20, 14.7444), 6.00049), 20.4195) < rank(((open + close) - (vwap + open)))) * -1) 14',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha86 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        87: {
            "formula": '(max(rank(decay_linear(delta(((close * 0.369701) + (vwap * (1 - 0.369701))), 1.91233), 2.65461)), Ts_Rank(decay_linear(abs(correlation(IndNeutralize(adv81, IndClass.industry), close, 13.4132)), 4.89768), 14.4535)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha87 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        88: {
            "formula": 'min(rank(decay_linear(((rank(open) + rank(low)) - (rank(high) + rank(close))), 8.06882)), Ts_Rank(decay_linear(correlation(Ts_Rank(close, 8.44728), Ts_Rank(adv60, 20.6966), 8.01266), 6.65053), 2.61957))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha88 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        89: {
            "formula": '(Ts_Rank(decay_linear(correlation(((low * 0.967285) + (low * (1 - 0.967285))), adv10, 6.94279), 5.51607), 3.79744) - Ts_Rank(decay_linear(delta(IndNeutralize(vwap, IndClass.industry), 3.48158), 10.1466), 15.3012))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha89 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        90: {
            "formula": '((rank((close - ts_max(close, 4.66719)))^Ts_Rank(correlation(IndNeutralize(adv40, IndClass.subindustry), low, 5.38375), 3.21856)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha90 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry', 'subindustry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        91: {
            "formula": '((Ts_Rank(decay_linear(decay_linear(correlation(IndNeutralize(close, IndClass.industry), volume, 9.74928), 16.398), 3.83219), 4.8667) - rank(decay_linear(correlation(vwap, adv30, 4.01303), 2.6809))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha91 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        92: {
            "formula": 'min(Ts_Rank(decay_linear(((((high + low) / 2) + close) < (low + open)), 14.7221), 18.8683), Ts_Rank(decay_linear(correlation(rank(low), rank(adv30), 7.58555), 6.94024), 6.80584))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha92 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        93: {
            "formula": '(Ts_Rank(decay_linear(correlation(IndNeutralize(vwap, IndClass.industry), adv81, 17.4193), 19.848), 7.54455) / rank(decay_linear(delta(((close * 0.524434) + (vwap * (1 - 0.524434))), 2.77377), 16.2664)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha93 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        94: {
            "formula": '((rank((vwap - ts_min(vwap, 11.5783)))^Ts_Rank(correlation(Ts_Rank(vwap, 19.6462), Ts_Rank(adv60, 4.02992), 18.0926), 2.70756)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha94 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        95: {
            "formula": '(rank((open - ts_min(open, 12.4105))) < Ts_Rank((rank(correlation(sum(((high + low) / 2), 19.1351), sum(adv40, 19.1351), 12.8742))^5), 11.7584))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha95 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        96: {
            "formula": '(max(Ts_Rank(decay_linear(correlation(rank(vwap), rank(volume), 3.83878), 4.16783), 8.38151), Ts_Rank(decay_linear(Ts_ArgMax(correlation(Ts_Rank(close, 7.45404), Ts_Rank(adv60, 4.13242), 3.65459), 12.6556), 14.0365), 13.4143)) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha96 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        97: {
            "formula": '((rank(decay_linear(delta(IndNeutralize(((low * 0.721001) + (vwap * (1 - 0.721001))), IndClass.industry), 3.3705), 20.4523)) - Ts_Rank(decay_linear(Ts_Rank(correlation(Ts_Rank(low, 7.87871), Ts_Rank(adv60, 17.255), 4.97547), 18.5925), 15.7152), 6.71659)) * -1) 15',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha97 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        98: {
            "formula": '(rank(decay_linear(correlation(vwap, sum(adv5, 26.4719), 4.58418), 7.18088)) - rank(decay_linear(Ts_Rank(Ts_ArgMin(correlation(rank(open), rank(adv15), 20.8187), 8.62571), 6.95668), 8.07206)))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha98 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        99: {
            "formula": '((rank(correlation(sum(((high + low) / 2), 19.8975), sum(adv60, 19.8975), 8.8136)) < rank(correlation(low, volume, 6.28259))) * -1)',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha99 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        100: {
            "formula": '(0 - (1 * (((1.5 * scale(indneutralize(indneutralize(rank(((((close - low) - (high - close)) / (high - low)) * volume)), IndClass.subindustry), IndClass.subindustry))) - scale(indneutralize((correlation(close, rank(adv20), 5) - rank(ts_argmin(close, 30))), IndClass.subindustry))) * (volume / adv20))))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha100 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount', 'industry', 'subindustry'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
        101: {
            "formula": '((close - open) / ((high - low) + .001))',
            "description": "按 WorldQuant 101 Formulaic Alphas 原稿对齐的 Alpha101 实现规格。",
            "required_fields": ['open', 'high', 'low', 'close', 'volume', 'amount'],
            "parameters": {"source": "official_appendix_a"},
            "notes": ["窗口参数按原稿取 floor 后实现。", "需要结合 factor 实现与 truth compare 进一步校验。"],
        },
    }
)


def alpha101_specs() -> list[FactorResearchSpec]:
    specs: list[FactorResearchSpec] = []
    for idx in range(1, 102):
        details = ALPHA101_IMPLEMENTED_DETAILS.get(idx, {})
        implemented = idx in ALPHA101_IMPLEMENTED_DETAILS
        specs.append(
            FactorResearchSpec(
                factor_name=f"alpha{idx}",
                library="Alpha101",
                version=ALPHA101_VERSION,
                display_name=f"Alpha101 #{idx}",
                factor_id=f"WQ101_{idx:03d}",
                source_document=ALPHA101_SOURCE,
                formula=str(details.get("formula", "")),
                description=str(details.get("description", "Alpha101 标准样板因子，后续将补齐公式、实现、真值与检验产物。")),
                frequency="day",
                sample_scope="A-share standard pool; remove ST, delisted, and newly listed securities when applicable.",
                required_fields=list(details.get("required_fields", ["open", "high", "low", "close", "volume", "amount"])),
                parameters=dict(details.get("parameters", {})),
                preprocessing=["adjust_prices", "align_trading_calendar", "winsorize_if_required"],
                neutralization=["industry", "size"],
                validation_targets=list(ALPHA101_COMMON_THRESHOLDS),
                tags=["alpha101", "worldquant", "formulaic-alpha"],
                notes=list(details.get("notes", [
                    "当前阶段先建立统一规格层和证明包模板。",
                    "具体公式将在接入官方附录或公开可核验参考实现后逐项补齐。",
                ])),
                metadata={
                    "status": "implemented" if implemented else "planned",
                    "implementation_stage": "code" if implemented else "spec",
                    "source_priority": "official_appendix_first",
                },
            )
        )
    return specs
